In [2]:
#import numpy
import numpy as np

In [3]:
#checking numpy version

print(np.__version__)

1.20.3


In [4]:
#creating a numpy number

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#use a tupple to create a numpy number

import numpy as np

arr = np.array((1,2,3,4,5))
print(arr)        

[1 2 3 4 5]


# TASK

In [14]:
#array list
list = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(list)
print(type(list))

[0.1 0.2 0.3 0.4 0.5]
<class 'numpy.ndarray'>


In [13]:
#array tupple
warna = np.array(("merah","kuning","hijau"))
print(warna)

['merah' 'kuning' 'hijau']


# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays)

In [8]:
#0-D arrays
import numpy as np
arr = np.array(40)
print(arr)

40


In [16]:
#create a 1-D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [19]:
#create a 2-D array containing three arrays
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[5,6,7]])
print(arr)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [23]:
#create a 3-D array with two 2-D arrays, both containing two arrays
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# TASK

In [24]:
#0-D arrays
warna = np.array("merah")
print(warna)

merah


In [25]:
#1-D arrays
import numpy as np
warna = np.array(["merah","kuning","hijau"])
print(warna)

['merah' 'kuning' 'hijau']


In [26]:
#2-D arrays
warna = np.array([["merah","kuning"],["biru","hijau"]])
print(warna)

[['merah' 'kuning']
 ['biru' 'hijau']]


In [27]:
#3-D arrays
warna = np.array([[["merah","kuning"],["biru","hijau"]],[["merah","kuning"],["biru","hijau"]]])
print(warna)

[[['merah' 'kuning']
  ['biru' 'hijau']]

 [['merah' 'kuning']
  ['biru' 'hijau']]]


# Check how many dimensions the arrays have

In [28]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6],[5,6,7]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Create an array with 5 dimensions and verify that it has 5 dimensions

In [30]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions : ', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions :  5


# TASK

In [36]:
#check how many dimensions the arrays have
import numpy as np

a = warna = np.array("merah")
b = np.array(["merah","kuning","hijau"])
c = np.array([["merah","kuning"],["biru","hijau"]])
d = np.array([[["merah","kuning"],["biru","hijau"]],[["merah","kuning"],["biru","hijau"]]])
e = np.array([[[["merah","kuning"]],[["biru","hijau"]]]])
f = np.array([[[[["merah","kuning"]],[["biru","hijau"]]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)

0
1
2
3
4
5


In [40]:
# Create an array with 5 dimensions and verify that it has 5 dimensions
warna = np.array([[[[["merah","kuning"]],[["biru","hijau"]]]]], ndmin=5)

print(warna)
print('number of dimensions : ', warna.ndim)

[[[[['merah' 'kuning']]

   [['biru' 'hijau']]]]]
number of dimensions :  5


In [41]:
#Get the first element from the following array
import numpy as np

arr = np.array([1,2,3,4])
print(arr[0])

1


In [42]:
#Get the second element from the following array
arr = np.array([1,2,3,4])
print(arr[1])

2


In [44]:
#Get the third and fourth element from the following array and add them
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


# TASK

In [45]:
data = np.array(["merah", 1, 2, "biru", 3, 4, "hijau", 5, 6, 7])
#2p
print(data[3:7])

['biru' '3' '4' 'hijau']


In [52]:
#3p
print(data[0:9:3])

['merah' 'biru' 'hijau']


In [53]:
#operasi index
print(data[0] + " " + data[3])

merah biru


In [55]:
#Access the element on the first row, second column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [57]:
#Access the element on the 2nd row, 5th column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1,4])

5th element on 2nd row:  10


In [58]:
#Access the third element of the 2nd array of the first array
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(arr[1,0,2])

9


# breakdown 

In [59]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(arr[1])

[[ 7  8  9]
 [10 11 12]]


In [60]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(arr[1,0])

[7 8 9]


In [61]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(arr[1,0,2])

9


# TASK

In [63]:
#1p
data = np.array([[[1,2,3], [4,5,6],[1,2,3]], [[7,8,9], [10,11,12],[1,2,3]]])
print(data[0])

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [65]:
#2p
data = np.array([[[1,2,3], [4,5,6],[1,2,3]], [[7,8,9], [10,11,12],[1,2,3]]])
print(arr[0,0])

[1 2 3]


In [66]:
#3p
data = np.array([[[1,2,3], [4,5,6],[1,2,3]], [[7,8,9], [10,11,12],[1,2,3]]])
print(arr[0,0,0])

1


# SLICING

In [20]:
#Slice elements from index 1 to index 5 from the following array
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [21]:
#Slice elements from index 4 to the end of the following array
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [22]:
#Slice from the index 3 from the end to the index 1 from the end
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [14]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:2])

[1 2]


In [70]:
#From the second elements, slice elements from index 1 to index 4 (not included)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4])

[7 8 9]


In [71]:
#From both elements, return index 2
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2, 2])

[3 8]


In [72]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2 , 1:4])

[[2 3 4]
 [7 8 9]]


# TASK

In [7]:
#3dim
data = np.array([[[1,2,3], [4,5,6],[1,2,3]], [[7,8,9], [10,11,12],[1,2,3]]])
print('1p 2p', data[1, 1:3])
print('2p 1p',data[1:3, 1])
print('2p 2p',data[1:3, 1:3])

1p 2p [[10 11 12]
 [ 1  2  3]]
2p 1p [[10 11 12]]
2p 2p [[[10 11 12]
  [ 1  2  3]]]


In [13]:
#[2p, 1p]
data = np.array([["merah","kuning","ungu"],["biru","hijau","pink"]])
print(data[0:1, 1])

['kuning']


In [19]:
#[2p, 2p]
data = np.array([["merah","kuning","ungu"],["biru","hijau","pink"]])
print(data[0:2, 1:2])

[['kuning']
 ['hijau']]
